language: c

install:
  - sudo apt-get update && sudo apt-get install -y --no-install-recommends python3-minimal python3-pip python3-setuptools
  - pip3 install platformio==4.2.1

script:
  - VERSION=$(git rev-parse --short HEAD)
  - HERE=$(readlink -f .)
  - sed -i -e 's|#define SKETCH_VERSION ".*"|#define SKETCH_VERSION "'$VERSION'"|' $PWD/ESP8266WirelessPrintAsync/ESP8266WirelessPrintAsync.ino
  - platformio run
  - BOARD=$(echo $BD | cut -d ":" -f 3)
  - |2
    pushd .pio/build
    for board_dir in */; do
        pushd "$board_dir"
        board=$(echo "$board_dir" | tr -d '/')
        rename "s|firmware|ESP8266WirelessPrintAsync_${board}_${VERSION}|" firmware.*
        popd
    done
    popd
  
after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh .pio/build/*/*.bin

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
