name: PlatformIO

on:
  pull_request:

jobs:
  pio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio==4.2.1
    - name: Run PlatformIO
      run: |
        VERSION=$(git rev-parse --short HEAD)
        HERE=$(readlink -f .)
        sed -i -e 's|#define SKETCH_VERSION ".*"|#define SKETCH_VERSION "'$VERSION'"|' $PWD/ESP8266WirelessPrintAsync/ESP8266WirelessPrintAsync.ino
        platformio run
        BOARD=$(echo $BD | cut -d ":" -f 3)
        pushd .pio/build
        for board_dir in */; do
          pushd "$board_dir"
          board=$(echo "$board_dir" | tr -d '/')
          rename "s|firmware|ESP8266WirelessPrintAsync_${board}_${VERSION}|" firmware.*
          popd
        done
        popd
    - uses: actions/upload-artifact@v2
      with:
        name: *WirelessPrint*.bin
        path: .pio/build/*/
